# .mergify.yml
pull_request_rules:
  - name: Automatic merge for owner's PRs when CI passes
    conditions:
      # --- Condições do PR ---
      - author=MeryylleA  # PR aberto por você
      - draft=false       # PR não é um rascunho

      # --- Condições dos Status Checks (CI) ---
      # Use os nomes exatos dos seus checks obrigatórios do ci.yml
      # O Mergify geralmente espera o nome completo do check como aparece no GitHub
      - check-success=Build & Test C++ Utilities
      - check-success=Test Python Suite
      # Se você tiver mais checks obrigatórios, adicione-os aqui.
      # Exemplo: - check-success=NomeDoWorkflow / NomeDoOutroJob

      # --- Outras Condições (Opcional) ---
      # - label!=work-in-progress  # Não pode ter a label 'work-in-progress'
      # - -conflict               # Sem conflitos de merge (Mergify já verifica isso por padrão antes de mergear)
      # - "approved-reviews-by=@lunaris-codex/core-team" # Se você tiver um time
    actions:
      merge:
        method: squash # Ou 'merge', 'rebase'
        # commit_message_template: | # Opcional: Template para a mensagem de commit do squash
        #  {{ title }} (#{{ number }})
        #
        #  {{ body }}
      # review: # Opcional: Fazer o Mergify aprovar o PR antes de mergear
      #   type: APPROVE
      #   message: "LGTM! CI passed and conditions met."
      # label: # Opcional: Adicionar uma label após o merge bem-sucedido
      #   add:
      #     - automerged
