[tool.black] # <--- FIXED
line-length = 127
exclude = '''
/(
    \.git
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv.*
    | _build
    | buck-out
    | build
    | dist
)/
'''

[tool.isort]
profile = "black"
line_length = 127
skip_glob = ["*/.venv*/*", "*/__pycache__/*", ".git/*"]
