name: Lunaris PR Greeter Bot (GitHub Models)

on:
  pull_request_target:
    types: [opened]

permissions:
  pull-requests: write

jobs:
  enable-auto-merge:
    runs-on: ubuntu-latest
    if: github.actor == 'MeryylleA' && github.event.pull_request.draft == false

    steps:
      - name: Enable GitHub Auto-Merge for Own PRs
        id: auto_merge_step
        uses: peter-evans/enable-pull-request-automerge@v3 
        with:
          token: ${{ secrets.LUNARIS_CODEX_PAT }} 
          pull-request-number: ${{ github.event.pull_request.number }}
          merge-method: squash
