# .github/workflows/pr_greeter_bot.yml
name: Lunaris PR Greeter Bot (GitHub Models)

on:
  pull_request_target:
    types: [opened]

permissions:
  pull-requests: write

jobs:
  greet-contributor:
    runs-on: ubuntu-latest
    # if: github.event.pull_request.user.login != 'MeryylleA' && github.event.pull_request.user.login != 'dependabot[bot]'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Create package.json and Install Dependencies
        run: |
          echo '{
            "type": "module",
            "dependencies": {
              "@azure-rest/ai-inference": "latest",
              "@azure/core-auth": "latest"
            }
          }' > package.json
          npm install
        working-directory: .

      - name: Generate Greeting Comment Text
        id: generate_comment_step
        env:
          GITHUB_PAT_FOR_MODELS: ${{ secrets.GH_MODELS_PAT }}
          PR_AUTHOR: ${{ github.event.pull_request.user.login }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          PR_TITLE: ${{ github.event.pull_request.title }}
        run: |
          # Run the Node.js script and capture its entire stdout
          # The Node.js script is designed to print the final comment (or an error/fallback) to stdout
          GENERATED_TEXT=$(node ./.github/scripts/generate_greeting.js)
          echo "Raw output from script: $GENERATED_TEXT" # For debugging
          
          # Ensure the output is properly escaped for multiline GitHub action output
          # Replace newlines with %0A, and other special chars if necessary for ::set-output
          # For $GITHUB_OUTPUT, multiline is handled by <<EOF syntax
          
          echo "comment_body<<EOF" >> $GITHUB_OUTPUT
          echo "$GENERATED_TEXT" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Post Greeting Comment to PR
        if: steps.generate_comment_step.outputs.comment_body != '' 
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }} 
          repository: ${{ github.repository }}
          issue-number: ${{ github.event.pull_request.number }}
          comment-identifier: pr-greeter-bot-greeting 
          edit-mode: replace 
          body: ${{ steps.generate_comment_step.outputs.comment_body }}
