name: Lunaris PR Greeter Bot (GitHub Models)

on:
  pull_request_target:
    types: [opened]

jobs:
  greet-contributor:
    runs-on: ubuntu-latest
    # Optional: Condition to not run for your own PRs or dependabot PRs
    # if: github.event.pull_request.user.login != 'MeryylleA' && github.event.pull_request.user.login != 'dependabot[bot]'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Needed to run a local script

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Or your preferred LTS version

      - name: Create package.json and Install Dependencies
        run: |
          echo '{
            "type": "module",
            "dependencies": {
              "@azure-rest/ai-inference": "latest",
              "@azure/core-auth": "latest"
            }
          }' > package.json
          npm install
        working-directory: . # Run in the root directory

      - name: Generate and Post Greeting Comment
        env:
          GITHUB_PAT_FOR_MODELS: ${{ secrets.GH_MODELS_PAT }} # PAT with models:read
          PR_AUTHOR: ${{ github.event.pull_request.user.login }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          PR_TITLE: ${{ github.event.pull_request.title }}
          REPO_FULL_NAME: ${{ github.repository }}
          GH_TOKEN_FOR_COMMENT: ${{ secrets.GITHUB_TOKEN }} # Standard GITHUB_TOKEN for posting comments
        run: node ./.github/scripts/generate_greeting.js # Path to your Node.js script
