# .github/workflows/release-drafter.yml

name: Release Drafter (Currently Disabled for Auto-Trigger) # Adicione uma nota no nome

on:
  workflow_dispatch: # Permite acionamento manual SOMENTE
  # push: # Comentado para desabilitar
  #   branches:
  #     - main 
  # pull_request: # Comentado para desabilitar
  #   types: [closed]
  #   branches:
  #     - main

permissions: 
  contents: write     
  pull-requests: read 

jobs:
  update_release_draft:
    name: Update Release Draft
    runs-on: ubuntu-latest
    # A condição if não é mais estritamente necessária se só temos workflow_dispatch,
    # mas não faz mal mantê-la.
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true) || github.event_name == 'workflow_dispatch'
    steps:
      - name: Draft Next Release
        uses: release-drafter/release-drafter@v6
        with:
          config-name: release-drafter-config.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
